// <auto-generated />
namespace CodeFirstTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GenreTitleHasUniqueIndex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenreTitleHasUniqueIndex));
        
        string IMigrationMetadata.Id
        {
            get { return "201706041500268_Genre Title Has Unique Index"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
